name: "Build Docker Image"

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_version:
        required: false
        type: string
        default: "*"
      working_directory:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile

jobs:
  build-image:
    name: Build Docker image to make sure it works
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - uses: actions/checkout@v2

      - name: Printing Inputs
        run: |
          echo "app_name: ${{ inputs.app_name }}"
          echo "app_version: ${{ inputs.app_version }}"
          echo "working_directory: ${{ inputs.working_directory }}"
          echo "dockerfile: ${{ inputs.dockerfile }}"

      - name: Build from Dockerfile
        id: build-image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: "${{ inputs.app_name }}:latest"
          context: "./${{ inputs.working_directory }}"
          file: "./${{ inputs.working_directory }}/${{ inputs.dockerfile }}"
          build-args: |
            APP_NAME=${{ inputs.app_name }}
            APP_VERSION=${{ inputs.app_version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.11.1
        with:
          image-ref: ${{ inputs.app_name }}:${{ inputs.app_version }}
          exit-code: '1'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

       #Upload results to the GitHub Security Tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'


