name: "Get the tag"
# If no tag associated to the latest commit, the default response is an empty string

on:
  workflow_call:
    outputs:
      git-tag:
        value: ${{ jobs.get-tag.outputs.ref }}

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        id: ref
        run: |
          ref="" 
          
          if grep -q "refs\/tags" <<< "$GITHUB_REF" ;then
            ref=$(echo $GITHUB_REF | cut -d / -f 3)
          fi
          
          echo "::set-output name=git-tag::$ref"
          echo "$ref"


