on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      java_version:
        required: false
        type: number
        default: 8
      profile:
        required: false
        type: string
        default: ""
    secrets:
      nexus_url:
        required: false


jobs:
  build-artifact:
    name: Java Maven Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Printing Inputs
        run: |
          echo "java_version:      ${{ inputs.java_version }}"
          echo "working_directory: ${{ inputs.working_directory}}"

      - name: "Set up JDK ${{ inputs.java_version }}"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}
          cache: 'maven'

      - name: Build with Maven -  no profile
        if: ${{ !inputs.profile }}
        working-directory: ${{ inputs.working_directory }}
        env:
          NEXUS_URL: ${{ secrets.nexus_url }}
        run: >-
          mvn -ntp --batch-mode clean test

      - name: Build with Maven - with Profile
        if: ${{ inputs.profile }}
        env:
          NEXUS_URL: ${{ secrets.nexus_url }}
        working-directory: ${{ inputs.working_directory }}
        run: >-
          mvn -ntp --batch-mode clean test -P ${{ inputs.profile }}
