on:
  workflow_call:
    inputs:
      imagestream_name:
        description: |
          Name of the image stream where the image to be scanned resides.
        type: string
        required: true
      source_image_tag:
        description: |
          The tag the image that needs to be scanned.
        type: string
        required: false
        default: latest
    secrets:
      openshift_namespace:
        required: true
      openshift_sa_name:
        required: true
      openshift_sa_password:
        required: true
      openshift_external_repository:
        required: true

jobs:
  build-scan:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to OpenShift Container Repository - Silver
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.openshift_external_repository }}
          username: ${{ secrets.openshift_sa_name }}
          password: ${{ secrets.openshift_sa_password }}

      - name: Pull Image for Scannning
        env:
          IMAGE: ${{secrets.openshift_external_repository}}/${{secrets.openshift_namespace}}/${{inputs.imagestream_name}}:${{inputs.source_image_tag}}
        run: |
          docker pull ${IMAGE}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{secrets.openshift_external_repository}}/${{secrets.openshift_namespace}}/${{inputs.imagestream_name}}:${{inputs.source_image_tag}}
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          exit-code: '1'
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: trivy-results.sarif
