on:
  workflow_call:
    inputs:
      build_config_name:
        description: |
          Name of the BuildConfig that will be triggered. We assume that the Image will also have the same name
        type: string
        required: true
      source_image_tag:
        description: |
          The tag the build config will initially create
        type: string
        required: false
        default: trivy
    secrets:
      openshift_namespace:
        required: true
      openshift_sa_name:
        required: true
      openshift_sa_password:
        required: true
      openshift_external_repository:
        required: true

jobs:
  build-scan:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to OpenShift Container Repository - Silver
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.openshift_external_repository }}
          username: ${{ secrets.openshift_sa_name }}
          password: ${{ secrets.openshift_sa_password }}
        
        #- name: Trigger Build Config
        #run: oc start-build ${{ inputs.build_config_name }} --wait

      - name: Pull Image for Scannning
        env:
          IMAGE: ${{secrets.openshift_external_repository}}/${{secrets.openshift_namespace}}/${{inputs.build_config_name}}:${{inputs.source_image_tag}}
        run: |
          docker pull image-registry.apps.silver.devops.gov.bc.ca/91beaa-tools/bc-paris-api:trivy

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: image-registry.apps.silver.devops.gov.bc.ca/91beaa-tools/bc-paris-api:trivy
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          exit-code: '1'
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: trivy-results.sarif
